// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aCuUmjypTz9xSAB530UXdjuInADMKTI',
    appId: '1:276745983249:web:748dfefbd5691abe5528b0',
    messagingSenderId: '276745983249',
    projectId: 'databasehandler-e2f44',
    authDomain: 'databasehandler-e2f44.firebaseapp.com',
    storageBucket: 'databasehandler-e2f44.firebasestorage.app',
    measurementId: 'G-7T6YQJQYDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFEuzcEtdSsTqeY2LNeQepqAkY1nHVDWw',
    appId: '1:276745983249:android:50edf4f42bfb8d1f5528b0',
    messagingSenderId: '276745983249',
    projectId: 'databasehandler-e2f44',
    storageBucket: 'databasehandler-e2f44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9H8qVa-YwgcEy2PQp3DU4-eO9hGJmX7o',
    appId: '1:276745983249:ios:495d8ac1eb166ca25528b0',
    messagingSenderId: '276745983249',
    projectId: 'databasehandler-e2f44',
    storageBucket: 'databasehandler-e2f44.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9H8qVa-YwgcEy2PQp3DU4-eO9hGJmX7o',
    appId: '1:276745983249:ios:495d8ac1eb166ca25528b0',
    messagingSenderId: '276745983249',
    projectId: 'databasehandler-e2f44',
    storageBucket: 'databasehandler-e2f44.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSlHgWZJyLQKGkm_FSoCcDfHHMOl8twkk',
    appId: '1:276745983249:web:7dc56fffc922b3da5528b0',
    messagingSenderId: '276745983249',
    projectId: 'databasehandler-e2f44',
    authDomain: 'databasehandler-e2f44.firebaseapp.com',
    storageBucket: 'databasehandler-e2f44.firebasestorage.app',
    measurementId: 'G-YQR233GP3N',
  );
}
