// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS-Ew_xWYItAZ-M8SsYeGmDnkWMtFWBtc',
    appId: '1:705876620420:web:6b8d775db538dbcdc3bed1',
    messagingSenderId: '705876620420',
    projectId: 'amadra-8c9bf',
    authDomain: 'amadra-8c9bf.firebaseapp.com',
    databaseURL: 'https://amadra-8c9bf-default-rtdb.firebaseio.com',
    storageBucket: 'amadra-8c9bf.firebasestorage.app',
    measurementId: 'G-8PSE91XKMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcGP-zLaADBUymgeizTBwtrKFXwPQUms',
    appId: '1:705876620420:android:2051dc23f49155f4c3bed1',
    messagingSenderId: '705876620420',
    projectId: 'amadra-8c9bf',
    databaseURL: 'https://amadra-8c9bf-default-rtdb.firebaseio.com',
    storageBucket: 'amadra-8c9bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP3B8n41YaJJAMaDrDRCD7U6mQ3uJNK-w',
    appId: '1:705876620420:ios:3d04aa432c33c689c3bed1',
    messagingSenderId: '705876620420',
    projectId: 'amadra-8c9bf',
    databaseURL: 'https://amadra-8c9bf-default-rtdb.firebaseio.com',
    storageBucket: 'amadra-8c9bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP3B8n41YaJJAMaDrDRCD7U6mQ3uJNK-w',
    appId: '1:705876620420:ios:3d04aa432c33c689c3bed1',
    messagingSenderId: '705876620420',
    projectId: 'amadra-8c9bf',
    databaseURL: 'https://amadra-8c9bf-default-rtdb.firebaseio.com',
    storageBucket: 'amadra-8c9bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS-Ew_xWYItAZ-M8SsYeGmDnkWMtFWBtc',
    appId: '1:705876620420:web:6b8d775db538dbcdc3bed1',
    messagingSenderId: '705876620420',
    projectId: 'amadra-8c9bf',
    authDomain: 'amadra-8c9bf.firebaseapp.com',
    databaseURL: 'https://amadra-8c9bf-default-rtdb.firebaseio.com',
    storageBucket: 'amadra-8c9bf.firebasestorage.app',
    measurementId: 'G-8PSE91XKMK',
  );
}
